name: Build and push CourseService

env:
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "delta-dev"
  APP_NAME: "course-service"
  IMAGE_REGISTRY: "image-registry.openshift-image-registry.svc:5000"  # Internal registry URL
  IMAGE_TAG: "${IMAGE_REGISTRY}/${OPENSHIFT_NAMESPACE}/${APP_NAME}:latest"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Update Git submodules
      run: git submodule update --init --recursive

    - name: Install oc
      uses: redhat-actions/openshift-tools-installer@v1
      with:
        oc: 4

    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}

    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        docker build -t ${APP_NAME}:latest -f CourseServiceAPI/Dockerfile .

    - name: Ensure ImageStream exists
      run: |
        IMAGE_STREAM=$(oc get imagestream ${APP_NAME} -n ${OPENSHIFT_NAMESPACE} --ignore-not-found)
        if [ -z "$IMAGE_STREAM" ]; then
          echo "ImageStream for ${APP_NAME} not found. Creating a new one..."
          oc create imagestream ${APP_NAME} -n ${OPENSHIFT_NAMESPACE}
        fi

    - name: Log in to OpenShift internal registry
      run: |
        # Assuming IMAGE_REGISTRY is directly specified as the OpenShift internal registry URL
        echo "Logging in to OpenShift internal registry..."
        echo "${{ env.OPENSHIFT_TOKEN }}" | docker login -u $(oc whoami) --password-stdin $IMAGE_REGISTRY

    - name: Tag and push image to internal registry
      run: |
        IMAGE_TAG="${IMAGE_REGISTRY}/${OPENSHIFT_NAMESPACE}/${APP_NAME}:latest"
        echo "Tagging and pushing Docker image to internal registry..."
        docker tag ${APP_NAME}:latest $IMAGE_TAG
        docker push $IMAGE_TAG

    - name: Deploy course-service
      run: |
        echo "Checking if DeploymentConfig for ${APP_NAME} exists..."
        if ! oc get deploymentconfig ${APP_NAME} -n ${OPENSHIFT_NAMESPACE} 2>/dev/null; then
          echo "DeploymentConfig for ${APP_NAME} not found. Creating a new one..."
          oc create deploymentconfig ${APP_NAME} --image=${IMAGE_TAG} -n ${OPENSHIFT_NAMESPACE}
        else
          echo "DeploymentConfig for ${APP_NAME} already exists."
        fi

    - name: Rollout and verify course-service
      run: |
        echo "Starting rollout for ${APP_NAME}..."
        
        # Check if a rollout is already in progress
        CURRENT_STATUS=$(oc rollout status deploymentconfig/${APP_NAME} -n ${OPENSHIFT_NAMESPACE} 2>&1)
        
        if [[ "$CURRENT_STATUS" == *"is already in progress"* ]]; then
          echo "Rollout is already in progress. Monitoring its status..."
        else
          oc rollout latest ${APP_NAME} -n ${OPENSHIFT_NAMESPACE}
        fi

        # Wait for the rollout to complete
        echo "Waiting for the rollout to complete..."
        oc rollout status deploymentconfig/${APP_NAME} -n ${OPENSHIFT_NAMESPACE} || {
          echo "Error: Rollout did not complete successfully."
          exit 1
        }

        echo "Waiting for the pod to be in 'Running' state..."
        for i in {1..12}; do
          POD_STATUS=$(oc get pods -n ${OPENSHIFT_NAMESPACE} -l app=${APP_NAME} -o jsonpath="{.items[0].status.phase}" 2>/dev/null)
          if [ "$POD_STATUS" == "Running" ]; then
            echo "Pod is running!"
            break
          elif [ "$POD_STATUS" == "CrashLoopBackOff" ]; then
            echo "Pod is in CrashLoopBackOff state. Fetching logs and describing the pod..."
            oc logs pod -l app=${APP_NAME} -n ${OPENSHIFT_NAMESPACE}
            oc describe pod -l app=${APP_NAME} -n ${OPENSHIFT_NAMESPACE}
            exit 1
          fi
          echo "Pod not ready yet. Retrying in 10 seconds..."
          sleep 10
        done

        if [ "$POD_STATUS" != "Running" ]; then
          echo "Error: Pod did not reach 'Running' state within the expected time."
          exit 1
        fi

        echo "Deployment successful and pod is running."
